-- Insertion des données de produits (50 produits)
INSERT INTO recipe (name, description, image)
VALUES 
('Huile essentielle de Lavande', 'Huile calmante et relaxante, idéale pour apaiser le stress et favoriser le sommeil.', 'https://mighty.tools/mockmind-api/content/product/1.jpg'),
('Huile essentielle de Menthe Poivrée', 'Aide à soulager les maux de tête, améliore la concentration et rafraîchit.', 'https://mighty.tools/mockmind-api/content/product/2.jpg'),
('Huile essentielle d’Arbre à Thé', 'Puissant antiseptique naturel, idéal pour traiter les problèmes de peau.', 'https://mighty.tools/mockmind-api/content/product/3.jpg'),
('Huile essentielle d’Eucalyptus', 'Apporte une aide respiratoire en cas de rhume et de congestion.', 'https://mighty.tools/mockmind-api/content/product/4.jpg'),
('Huile essentielle de Citron', 'Connue pour ses propriétés énergisantes et purifiantes, idéale pour le ménage naturel.', 'https://mighty.tools/mockmind-api/content/product/5.jpg'),
('Huile essentielle de Romarin', 'Aide à stimuler la mémoire, soulager les douleurs musculaires.', 'https://mighty.tools/mockmind-api/content/product/6.jpg'),
('Huile essentielle de Ylang-Ylang', 'Relaxante, elle aide à apaiser le corps et l’esprit, parfaite pour une ambiance zen.', 'https://mighty.tools/mockmind-api/content/product/7.jpg'),
('Huile essentielle d’Orange Douce', 'Apporte joie et optimisme, elle aide à créer une atmosphère positive.', 'https://mighty.tools/mockmind-api/content/product/8.jpg'),
('Huile essentielle de Camomille', 'Apaise l’anxiété et améliore le sommeil, idéale pour les moments de détente.', 'https://mighty.tools/mockmind-api/content/product/9.jpg'),
('Huile essentielle de Patchouli', 'Utilisée pour équilibrer les émotions et apaiser les tensions.', 'https://mighty.tools/mockmind-api/content/product/10.jpg'),
('Huile essentielle de Bergamote', 'Aide à lutter contre le stress et la dépression.', 'https://mighty.tools/mockmind-api/content/product/11.jpg'),
('Huile essentielle de Thym', 'Idéale pour renforcer le système immunitaire et traiter les infections respiratoires.', 'https://mighty.tools/mockmind-api/content/product/12.jpg'),
('Huile essentielle de Niaouli', 'Favorise la respiration et agit comme un antiviral puissant.', 'https://mighty.tools/mockmind-api/content/product/13.jpg'),
('Huile essentielle de Géranium', 'Connue pour ses propriétés apaisantes, elle aide à équilibrer les émotions.', 'https://mighty.tools/mockmind-api/content/product/14.jpg'),
('Huile essentielle de Clou de Girofle', 'Excellent antiseptique et analgésique pour les soins dentaires.', 'https://mighty.tools/mockmind-api/content/product/15.jpg'),
('Huile essentielle de Sauge Sclarée', 'Soulage les douleurs menstruelles et favorise l’équilibre hormonal.', 'https://mighty.tools/mockmind-api/content/product/16.jpg'),
('Huile essentielle de Bois de Santal', 'Calme l’esprit et favorise la méditation et la relaxation.', 'https://mighty.tools/mockmind-api/content/product/17.jpg'),
('Huile essentielle de Cèdre', 'Apaisante et tonifiante, idéale pour la peau et les cheveux.', 'https://mighty.tools/mockmind-api/content/product/18.jpg'),
('Huile essentielle de Jasmin', 'Connu pour ses propriétés aphrodisiaques et relaxantes.', 'https://mighty.tools/mockmind-api/content/product/19.jpg'),
('Huile essentielle de Vétiver', 'Réduit l’anxiété et apporte un sentiment d’ancrage et de sérénité.', 'https://mighty.tools/mockmind-api/content/product/20.jpg'),
('Huile essentielle de Fenouil', 'Aide à la digestion et à l’équilibre hormonal.', 'https://mighty.tools/mockmind-api/content/product/21.jpg'),
('Huile essentielle de Cannelle', 'Stimule la circulation et aide à soulager les douleurs musculaires.', 'https://mighty.tools/mockmind-api/content/product/22.jpg'),
('Huile essentielle de Genévrier', 'Détoxifiante, elle aide à lutter contre la rétention d’eau et la fatigue.', 'https://mighty.tools/mockmind-api/content/product/23.jpg'),
('Huile essentielle de Myrrhe', 'Puissant antiseptique, utilisée pour les soins de la peau.', 'https://mighty.tools/mockmind-api/content/product/24.jpg'),
('Huile essentielle de Palmarosa', 'Hydratante et régénérante, idéale pour les peaux sèches et irritées.', 'https://mighty.tools/mockmind-api/content/product/25.jpg'),
('Huile essentielle de Verveine', 'Apporte calme et relaxation, idéale pour lutter contre l’insomnie.', 'https://mighty.tools/mockmind-api/content/product/26.jpg'),
('Huile essentielle de Marjolaine', 'Apaisante et réconfortante, utilisée pour soulager le stress et l’anxiété.', 'https://mighty.tools/mockmind-api/content/product/27.jpg'),
('Huile essentielle de Basilic', 'Stimule l’esprit et aide à lutter contre la fatigue mentale.', 'https://mighty.tools/mockmind-api/content/product/28.jpg'),
('Huile essentielle de Curcuma', 'Antioxydante, elle aide à réduire l’inflammation et à soulager les douleurs.', 'https://mighty.tools/mockmind-api/content/product/29.jpg'),
('Huile essentielle de Lavandin', 'Similaire à la lavande, elle est relaxante et soulage les tensions musculaires.', 'https://mighty.tools/mockmind-api/content/product/30.jpg'),
('Huile essentielle de Citronnelle', 'Repousse les insectes et rafraîchit l’air.', 'https://mighty.tools/mockmind-api/content/product/31.jpg'),
('Huile essentielle de Cade', 'Antifongique et antibactérienne, utilisée pour les problèmes de peau.', 'https://mighty.tools/mockmind-api/content/product/32.jpg'),
('Huile essentielle de Cardamome', 'Aide à la digestion et stimule l’esprit.', 'https://mighty.tools/mockmind-api/content/product/33.jpg'),
('Huile essentielle de Menthe Verte', 'Apporte fraîcheur et aide à la digestion.', 'https://mighty.tools/mockmind-api/content/product/34.jpg'),
('Huile essentielle d’Encens', 'Favorise la méditation et apaise l’esprit.', 'https://mighty.tools/mockmind-api/content/product/35.jpg'),
('Huile essentielle de Ciste', 'Régénérante pour la peau et aide à la cicatrisation.', 'https://mighty.tools/mockmind-api/content/product/36.jpg'),
('Huile essentielle de Bois de Hô', 'Apaisante et équilibrante, idéale pour les soins de la peau.', 'https://mighty.tools/mockmind-api/content/product/37.jpg'),
('Huile essentielle de Citron Vert', 'Rafraîchissante et énergisante, aide à purifier l’air.', 'https://mighty.tools/mockmind-api/content/product/38.jpg'),
('Huile essentielle de Pamplemousse', 'Énergisante et tonifiante, aide à lutter contre la fatigue.', 'https://mighty.tools/mockmind-api/content/product/39.jpg'),
('Huile essentielle de Mandarine', 'Apporte calme et relaxation, idéale pour le sommeil des enfants.', 'https://mighty.tools/mockmind-api/content/product/40.jpg'),
('Huile essentielle de Laurier Noble', 'Renforce le système immunitaire et soulage les infections respiratoires.', 'https://mighty.tools/mockmind-api/content/product/41.jpg'),
('Huile essentielle d’Achillée Millefeuille', 'Utilisée pour soulager les inflammations et les irritations cutanées.', 'https://mighty.tools/mockmind-api/content/product/42.jpg'),
('Huile essentielle de Gaulthérie', 'Anti-inflammatoire puissant, soulage les douleurs articulaires et musculaires.', 'https://mighty.tools/mockmind-api/content/product/43.jpg'),
('Huile essentielle de Bois de Rose', 'Régénérante et revitalisante pour la peau, idéale pour le vieillissement cutané.', 'https://mighty.tools/mockmind-api/content/product/44.jpg'),
('Huile essentielle d’Estragon', 'Aide à la digestion et soulage les spasmes digestifs.', 'https://mighty.tools/mockmind-api/content/product/45.jpg'),
('Huile essentielle de Menthe des Champs', 'Tonique et rafraîchissante, stimule la concentration.', 'https://mighty.tools/mockmind-api/content/product/46.jpg'),
('Huile essentielle de Néroli', 'Apaisante et relaxante, idéale pour calmer les tensions émotionnelles.', 'https://mighty.tools/mockmind-api/content/product/47.jpg'),
('Huile essentielle de Bois de Cèdre Atlas', 'Équilibrante, elle aide à la méditation et la relaxation profonde.', 'https://mighty.tools/mockmind-api/content/product/48.jpg');
